services:
  database:
    image: 'postgres:13'
    restart: always
    environment:
      POSTGRES_USER: root1
      POSTGRES_PASSWORD: root1
      POSTGRES_DB: scholarship_portal
    ports:
      - 6000:5432
    volumes:
      - /var/lib/postgresql/data
